import { Poppins } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { NextUIProvider } from "@nextui-org/react";
// import {SessionProvider} from "next-auth/react"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Agent Portal",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { lang } = params;
  const messages = await getMessages();
  console.log("i am RootLayout");
  return (
    <html lang={lang} dir={lang === "ar" ? "rtl" : "ltr"}>
      <body className={`${poppins.className} antialiased`}>
        {/* <SessionProvider session={session} basePath="/" refetchInterval={2 * 60} refetchOnWindowFocus={true}> */}
          <NextUIProvider>
            <NextIntlClientProvider messages={messages}>
              {children}
            </NextIntlClientProvider>
          </NextUIProvider>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
