import {Poppins} from "next/font/google"
import "./globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['400','500','600','700','800','900']
});

export const metadata = {
  title: "Agent Portal",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { lang } = params;
  const messages = await getMessages();
console.log('i am layout')
  return (
    <html lang={lang} dir={lang === "ar" ? "rtl" : "ltr"}>
 
      <body
        className={`${poppins.className} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}