import { Poppins } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { NextUIProvider } from "@nextui-org/react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Agent Portal",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { lang } = params;
  const messages = await getMessages();
  console.log("i am layout");
  return (
    <html lang={lang} dir={lang === "ar" ? "rtl" : "ltr"}>
      <body className={`${poppins.className} antialiased`}>
        <NextUIProvider>
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
